fix: switch account modal ui bug
blockstack/stacks-wallet-web pull request #5705
Opened 2024-07-30 10:54 UTC by alter-eggo

> Try out Leather build 5cbb598 — [Extension build](https://github.com/leather-io/extension/actions/runs/10175990921), [Test report](https://leather-io.github.io/playwright-reports/fix-switch-modal-jump), [Storybook](https://fix-switch-modal-jump--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix-switch-modal-jump)

This pr fixes in full mode: 
- switch account modal "jump" on open
- problem of too many accounts rendered on open

https://github.com/user-attachments/assets/ee0ffe16-3c78-4bd1-aed6-614b1d1a1fba

![Screenshot 2024-07-30 at 14 51 23](https://github.com/user-attachments/assets/4cf1e998-f403-4e84-ac35-6a0a4b99860b)

2024-07-30 11:12 UTC, pete-watters commented on src/app/common/media-query-provider.tsx
> +export function MediaQueryProvider({ children }: MediaQueryProviderProps) {
Maybe we can use `HasChildren` for these props?

2024-07-30 11:14 UTC, pete-watters approved these changes
Thanks for fixing this 👍 

I wonder if there is a better way than wrapping the whole app in another provider? 

It would be good to open an issue also, describing the bug, so that we can link the fix and have it in the release notes

2024-07-30 11:25 UTC, alter-eggo commented
@pete-watters we can put it to `Container` component and pass as prop to switch acc dialog. 
I just though this approach is more extendable, but if you guys have some strong opinion here, I can refactor it to prop

2024-07-30 11:32 UTC, pete-watters commented
> @pete-watters we can put it to `Container` component and pass as prop to switch acc dialog. I just though this approach is more extendable, but if you guys have some strong opinion here, I can refactor it to prop

I was just curious. I'm happy to go with this for now and merge it then we can consider improving it if we need to. I'm working on fixing the `Container` so we can check it out then. 

Thanks for fixing it!

2024-07-30 12:15 UTC, kyranjamie requested changes
Not sure this is the best solution. Why do we need to create the whole new context just to read a CSS query? Is there a problem where on initial render the value is null, hence the jump? Can you explain how your solution fixes the problem and behaves differently? 

If we render many list items on open, we can check the settings of Virtuoso, which lets you configure how far ahead to render?

2024-07-30 13:22 UTC, alter-eggo commented
> Is there a problem where on initial render the value is null, hence the jump

[useMediaQuery](https://github.com/leather-io/extension/blob/dev/src/app/common/hooks/use-media-query.ts) returns `false` on initial render which leads to "jump". 
now once app is opened, callback fires and sets the proper value, which we pass to dialog then. 

> If we render many list items on open, we can check the settings of Virtuoso, which lets you configure how far ahead to render?

I checked virtuoso settings, it provides `overscan` and `increaseViewportBy` settings. I've set both to 0 and it haven't help. 
I believe problem is in these margins (on the screenshot). it seems virtuoso incorrectly calculates the item height bc of them. 
when I remove it, we can see that it renders proper amount of rows (16)

![Screenshot 2024-07-30 at 17 09 48](https://github.com/user-attachments/assets/58c6fbba-ce53-43f3-a3fa-e6a9f5f02509)
![Screenshot 2024-07-30 at 17 22 15](https://github.com/user-attachments/assets/1610cdf9-1cc7-482f-804b-8e5b56020c2f)

2024-07-30 13:25 UTC, alter-eggo commented
I changed `my` to `py` and it helped btw

2024-07-30 14:00 UTC, kyranjamie commented
> [useMediaQuery](https://github.com/leather-io/extension/blob/dev/src/app/common/hooks/use-media-query.ts) returns false on initial render which leads to "jump".

Maybe this can be fixed within the query itself? The `useState` defaults to false. Does it need to? What if we do a query match on first render?

```ts
  const [matches, setMatches] = useState(() => window.matchMedia(query).matches);
```

2024-07-30 19:19 UTC, alter-eggo commented
@kyranjamie yeah, your suggestion works, thanks! removed provider

2024-07-30 19:28 UTC, kyranjamie approved these changes
Awesome, thanks for investigating 👌🏼

2024-07-31 05:00 UTC, pete-watters commented on src/app/ui/components/virtuoso.tsx
> +        paddingTop: '12px',
Will `space.03` work for this also?

2024-07-31 05:02 UTC, pete-watters commented
Thanks for updating this @alter-eggo 👏 Werner opened this bug yesterday about the last entry being cut off on Ledger: https://github.com/leather-io/extension/issues/5706 , maybe the change to use `py` also fixes that?

2024-07-31 05:43 UTC, alter-eggo commented on src/app/ui/components/virtuoso.tsx
> +        paddingTop: '12px',
yeah, will fix

2024-07-31 07:26 UTC, alter-eggo commented
@pete-watters yeah, seems it is fixed

2024-07-31 07:53 UTC, merged