feat: add cancel transaction, ref #LEA-958
blockstack/stacks-wallet-web pull request #5920
Opened 2024-10-24 12:35 UTC by alter-eggo

> Try out Leather build 53a7e31 — [Extension build](https://github.com/leather-io/extension/actions/runs/11592147513), [Test report](https://leather-io.github.io/playwright-reports/feat-cancel-tx), [Storybook](https://feat-cancel-tx--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=feat-cancel-tx)

This pr adds option to cancel stx transaction, also adds tests for increase and cancel stx transaction

@Aman-zishan thanks a lot for your work on this

2024-10-24 13:04 UTC, kyranjamie commented on src/app/components/stacks-transaction-item/stacks-transaction-action-menu.tsx
> +interface Props {
use full name like other components 🙏🏼

2024-10-29 13:13 UTC, fbwoolf commented on src/app/components/stacks-transaction-item/stacks-transaction-item.tsx
> +      action === 'increaseFee'
Maybe pull this out as a defined type and use `increase-fee`?

2024-10-29 13:14 UTC, fbwoolf approved these changes

2024-10-29 13:28 UTC, pete-watters commented on src/shared/route-urls.ts
> +  IncreaseStacksFee = '/increase-fee/stacks/:txid',
I guess `/increase-fee/btc` should also update here?

2024-10-29 13:37 UTC, pete-watters commented
This code looks good but I am confused about how to cancel a transaction. 

I tried to cancel a stacks transfer and I see this:
![Screenshot 2024-10-29 at 13 36 13](https://github.com/user-attachments/assets/b45662e1-17f5-4411-a63e-476084a11b9c)

Do I need to choose a fee and then submit to cancel? 🤔

2024-10-29 13:37 UTC, pete-watters approved these changes
👍

2024-10-29 13:38 UTC, alter-eggo commented
@314159265359879 could you test this build please

2024-10-29 13:39 UTC, alter-eggo commented
@pete-watters yeah, as I understand you need to increase fee a bit to cancel tx

2024-10-30 00:26 UTC, 314159265359879 commented
Thanks for this @alter-eggo 
The prefilled fee here should default to 0.000001 STX more than the current fee for the transaction being replaced. That way the user can already click submit (now it is not allowed unless they click atleast 2x, which will be excessive in almost all cases).
With a 0.000001 STX increase the "submit" button can be light up right away (ready to click, and then increasing the fee further is optional).

![image](https://github.com/user-attachments/assets/976da07b-7ca2-4a21-bc8b-3447b0be9247)

For context, STX transfers don't usually need a higher fee to get included in a block (unlike some contract calls and contract deployments) they require very little of the "block space".  

![image](https://github.com/user-attachments/assets/51aa9be9-fb09-41ba-897c-9596e38051b5)

With the change above. I opt to remove "A higher fee can help replace the old transaction." from the explainer. Because in most cases we'll set the right fee (just 0.000001 STX more then current). Leaving it in there may make users think that they have to set a much higher fee, which is not actually the case. There is simply no guarantee the old transaction won't get picked up while the new one gets propagated over the network to replace it. That process is not faster with a higher fee just depends on the connectedness of nodes and timing of miners/BTC blocks.

2024-10-30 00:44 UTC, 314159265359879 requested changes
See comments above.

2024-10-30 10:24 UTC, alter-eggo commented on src/app/components/stacks-transaction-item/stacks-transaction-item.tsx
> +      action === 'increaseFee'
added enum

2024-10-30 10:25 UTC, alter-eggo commented on src/shared/route-urls.ts
> +  IncreaseStacksFee = '/increase-fee/stacks/:txid',
how `/increase-fee/btc` should be changed here? 🤔

2024-10-30 10:27 UTC, pete-watters commented on src/shared/route-urls.ts
> +  IncreaseStacksFee = '/increase-fee/stacks/:txid',
I just saw you changed:
- `IncreaseStxFee` -> `IncreaseStacksFee` 
- `'/increase-fee/stx/:txid'` -> `/increase-fee/stacks/:txid`

Should we also have `IncreaseBitcoinFee`  & ``/increase-fee/bitcoin/:txid` then?

2024-10-30 10:30 UTC, alter-eggo commented on src/shared/route-urls.ts
> +  IncreaseStacksFee = '/increase-fee/stacks/:txid',
no, we don't need, we pass tx in state for btc. I haven't touched btc increase flow in this pr

2024-10-30 10:38 UTC, pete-watters commented on src/shared/route-urls.ts
> +  IncreaseStacksFee = '/increase-fee/stacks/:txid',
OK 👍 I was just suggesting for consistency as there is a mix of conventions here

2024-10-30 11:20 UTC, alter-eggo commented
thanks @314159265359879 fixed this

2024-10-30 12:57 UTC, 314159265359879 approved these changes
Looking great!

2024-10-30 14:27 UTC, merged